name: file_magic_number
description: "A Flutter package to detect file types based on their magic number instead of MIME types. Supports Flutter on mobile, desktop, and web without native code."
version: 0.7.0
homepage: https://github.com/vicajilau/file_magic_number

environment:
  sdk: ^3.7.0

dependencies:
  web: ^1.1.0

dev_dependencies:
  flutter_lints: ^5.0.0
  test: ^1.25.15

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
